input_file = "source/phantom_ischemic.hdf5"
output_dir = "out"
target_region = [-30e-3, 30e-3, 20e-3, 90e-3]
learning_rate = 1e-3
batch_size = 2048
n_iterations_per_frame = 7000
n_frames = 1
n_fbins = 4096
first_frame = 0
seed = 0
min_distance_between_peaks_wl = 2.0
attenuation_coef = 0.00 # [Np/cm/MHz]
das_dynamic_range = 80
f_number = 0.1
tgc_per_256_samples = 1.0
peak_detection_threshold = 0.01
max_n_peaks = 1024
transmits = "30"
remove_weak_scatters_threshold = 0.0
use_analytical_waveform = true
gradient_accumulation_steps = 32
sweep_step_size = 6
initialize_randomly = false
l1_regularization = 0.0
l2_regularization = 0.0
# t_peak = 2.76e-07
expected_velocity_range_wl_per_frame = [0.0, 2.0]
harmonic = true
is_2d = true